#!/bin/sh

function bootstrap() {
    cd ~ || exit;
    git clone --separate-git-dir="$HOME/.dotfiles" \
        https://github.com/jssee/.dotfiles.git tmp_dotfiles

    rsync --recursive --verbose --exclude ".git" \
        --exclude "README.md" \
        --exclude "bootstrap" \
        --no-perms \
        tmp_dotfiles/ "$HOME/";

    rm -r tmp_dotfiles;
}

read -rp "This process overwites existing files in your home directory. Continue? (y/n): " -n 1;

if [[ $REPLY =~ ^[Yy]$ ]]; then
    bootstrap;
    printf "\nMachine bootsrapping complete. Run `make all` to finish setting up brew, asdf, and some macos defaults.\n"
fi;
# vim: set tabstop=4:softtabstop=4:shiftwidth=4:noexpandtab
