tap "homebrew/services"
tap "cormacrelf/tap"

# utilities
brew "coreutils"
brew "dark-notify"
brew "fd"
brew "fish"
brew "fzy"
brew "gnupg"
brew "jq"
brew "moreutils"
brew "openssl"
brew "renameutils"
brew "ripgrep"
brew "tree"

# coding tools
brew "difftastic"
brew "direnv"
brew "gh"
brew "git"
brew "neovim"
brew "openconnect"
brew "postgresql"

# apps
cask "arc"
cask "1password"
cask "figma"
cask "iina"
cask "kap"
cask "raycast"
cask "rectangle-pro"

