#!/usr/bin/env bash

# close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# ask for the administrator password upfront
sudo -v

# keep-alive: update existing `sudo` time stamp until script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# trackpad: 
defaults write com.apple.AppleMultitouchTrackpad "TrackpadThreeFingerDrag" -bool "true"
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad "Clicking" -bool "true"

# finder:
defaults write com.apple.finder "ShowPathbar" -bool "true"
defaults write com.apple.finder "FXDefaultSearchScope" -string "SCcf"
defaults write com.apple.finder "NewWindowTarget" -string "PfDe"
defaults write com.apple.finder "NewWindowTargetPath" -string "file://${HOME}/Desktop/"
defaults write com.apple.finder "ShowStatusBar" -bool "true"
defaults write com.apple.finder "FXPreferredViewStyle" -string "clmv"


# dock:
defaults write com.apple.dock "show-recents" -bool "false"
defaults write com.apple.dock "wvous-bl-corner" -int 11
defaults write com.apple.dock "wvous-br-corner" -int 4
defaults write com.apple.dock "persistent-apps" -array
defaults write com.apple.dock "autohide" -bool "true"

# system preferences:
defaults write com.apple.systempreferences "NSQuitAlwaysKeepsWindows" -bool "false"

# cleanup: 
# kill all affected apps
for app in "Finder" \
  "Dock" \
  "cfprefsd" \
  "SystemUIServer"; do
  killall "${app}" &> /dev/null
done

