[package]
disabled = true

[cmd_duration]
format = "[$duration]($style)"

[git_branch]
symbol = ""

[git_status]
style = "purple"
ahead = "⇡${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
modified = "✶"

[nodejs]
symbol = "🧩 "
